import { colors } from "@shared/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    flex: 1,
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  headerActions: {
    position: "relative",
    flexDirection: "row",
    gap: 8,
  },
  addButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  createMenu: {
    position: "absolute",
    top: 50,
    right: 0,
    backgroundColor: colors.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    minWidth: 120,
    zIndex: 100,
  },
  createMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  createMenuItemText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "500",
  },
  listContent: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  eventCard: {
    backgroundColor: "#1A2429",
    borderRadius: 16,
    marginBottom: 1,
    padding: 16,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    borderLeftWidth: 0,
    borderWidth: 1,
    borderColor: "#23343C",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  mainTaskRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flex: 1,
  },
  eventContent: {
    flex: 1,
    marginRight: 12,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    flex: 1,
  },
  eventDescription: {
    fontSize: 13,
    color: colors.secondary,
    marginBottom: 8,
    lineHeight: 18,
  },
  descriptionContainer: {
    marginBottom: 8,
    paddingVertical: 4,
  },
  eventTime: {
    fontSize: 12,
    color: "#3FD3FF",
    marginBottom: 4,
    fontWeight: "500",
  },
  eventLocation: {
    fontSize: 12,
    color: "#8DA7B5",
    marginTop: 4,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    gap: 4,
  },
  metaLabel: {
    fontSize: 12,
    color: "#8DA7B5",
    fontWeight: "500",
    marginLeft: 4,
  },
  metaValue: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "400",
  },
  eventActions: {
    flexDirection: "row",
    gap: 12,
  },
  taskCard: {
    borderColor: colors.dot,
    borderWidth: 1,
  },
  itemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 6,
    gap: 8,
  },
  taskBadge: {
    // backgroundColor: "#FF9500",
    borderColor: colors.dot,
    borderStyle: "solid",
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  taskBadgeText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#fff",
  },
  editButton: {
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  deleteButton: {
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  loadingIndicator: {
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 18,
    color: "#8DA7B5",
    marginBottom: 20,
    textAlign: "center",
  },
  addEventButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 8,
  },
  addEventButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  bottomNav: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#151F24",
    borderRadius: 18,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#22323A",
  },
  bottomItem: {
    alignItems: "center",
    gap: 4,
  },
  bottomItemActive: {
    alignItems: "center",
    gap: 4,
  },
  bottomLabel: {
    fontSize: 10,
    color: "#6E808A",
  },
  bottomLabelActive: {
    fontSize: 10,
    color: "#54D2FF",
    fontWeight: "600",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
  },
  cancelButton: {
    color: "#8DA7B5",
    fontWeight: "500",
    fontSize: 16,
  },
  saveButton: {
    color: colors.primary,
    fontWeight: "600",
    fontSize: 16,
  },
  modalContent: {
    flex: 1,
    padding: 16,
  },
  formGroup: {
    marginBottom: 24,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#23343C",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.text,
    backgroundColor: "#1A2429",
  },
  pickerRow: {
    flexDirection: "row",
    gap: 8,
  },
  pickerInput: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pickerText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "500",
  },
  textArea: {
    textAlignVertical: "top",
    minHeight: 100,
    paddingTop: 10,
  },
  hint: {
    fontSize: 12,
    color: "#8DA7B5",
    marginTop: 6,
  },
  detailModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  detailModalContent: {
    backgroundColor: "#1A2429",
    borderRadius: 12,
    maxHeight: "80%",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#23343C",
  },
  detailModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  detailModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  detailModalActions: {
    flexDirection: "row",
    gap: 12,
  },
  detailModalBody: {
    padding: 16,
  },
  detailSection: {
    marginBottom: 20,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.primary,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  detailTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
  },
  detailText: {
    fontSize: 14,
    color: colors.secondary,
    lineHeight: 20,
  },
  detailLink: {
    fontSize: 14,
    color: "#54D2FF",
    textDecorationLine: "underline",
    lineHeight: 20,
  },
  detailListItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  detailListMeta: {
    fontSize: 12,
    color: "#8DA7B5",
  },
  tasksContainer: {
    marginBottom: 4,
  },
  chevron: {
    marginRight: 8,
  },
  subtasksContainer: {
    marginTop: 12,
    marginBottom: 0,
    marginLeft: -16,
    marginRight: -16,
    paddingHorizontal: 16,
    paddingVertical: 0,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#23343C",
  },
  subtaskItem: {
    backgroundColor: "transparent",
    borderRadius: 0,
    marginBottom: 0,
    paddingVertical: 8,
    paddingHorizontal: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  subtaskContent: {
    flex: 1,
    marginRight: 12,
  },
  subtaskTitle: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
    marginBottom: 4,
  },
  subtaskNotes: {
    fontSize: 12,
    color: colors.secondary,
    marginBottom: 4,
    lineHeight: 16,
  },
  subtaskTime: {
    fontSize: 11,
    color: colors.secondary,
    marginBottom: 0,
    fontWeight: "400",
  },
  subtaskActions: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  checkboxContainer: {
    marginRight: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxContainerRight: {
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  completedCard: {
    // Keep same design, no opacity or background change
  },
  completedText: {
    textDecorationLine: "line-through",
  },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    gap: 12,
  },
  startButton: {
    backgroundColor: "#5AC8FA",
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  startButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  subtaskStartButton: {
    backgroundColor: "#5AC8FA",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
  },
  subtaskStartButtonText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "600",
  },
});
