import { colors } from "@shared/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  taskQueueModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(4, 10, 13, 0.65)",
    justifyContent: "flex-end",
  },
  taskQueueModalContent: {
    height: "88%",
    backgroundColor: "#0F1A1F",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: "#1E3640",
    borderBottomWidth: 0,
    position: "relative",
  },
  taskQueueModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#1E3640",
  },
  taskQueueModalTitleContainer: {
    flex: 1,
    marginRight: 12,
  },
  taskQueueModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
    flexShrink: 1,
  },
  taskQueueHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  taskQueueHeaderIconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#15262D",
    borderWidth: 1,
    borderColor: "#24424E",
  },
  taskQueueBody: {
    flex: 1,
  },
  taskQueueBodyContent: {
    flexGrow: 1,
    padding: 18,
    paddingBottom: 36,
    gap: 18,
  },
  taskQueueMainSection: {
    borderColor: "#24424E",
    padding: 14,
    gap: 10,
  },
  taskQueueSubtasksSection: {
    gap: 10,
  },
  taskQueueSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#8AE8FF",
    marginBottom: 4,
  },
  taskQueueFieldRow: {
    gap: 4,
  },
  taskQueueFieldLabel: {
    color: "#80A1AF",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  taskQueueFieldValue: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  taskQueueEditableInput: {
    borderWidth: 1,
    borderColor: "#24424E",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    backgroundColor: "#15262D",
    fontSize: 14,
  },
  taskQueueEditableMultilineInput: {
    minHeight: 90,
  },
  taskQueueNoSubtasksText: {
    fontSize: 14,
    color: "#96B0BD",
  },
  taskQueueEmptyState: {
    paddingHorizontal: 20,
    paddingVertical: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  taskQueueEmptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
  },
  taskQueueEmptyText: {
    color: "#9AB3BF",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 21,
  },
  taskQueueUpdatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(10, 20, 25, 0.7)",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    zIndex: 10,
  },
  taskQueueUpdatingText: {
    color: "#E5F7FF",
    fontSize: 14,
    fontWeight: "600",
  },
  subtaskAccordionCard: {
    backgroundColor: "#16242B",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#223D47",
    marginBottom: 10,
    overflow: "hidden",
  },
  subtaskAccordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  subtaskAccordionTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    paddingRight: 8,
  },
  subtaskOrderBadge: {
    minWidth: 34,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: "#1D3B47",
    color: "#78E5FF",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  subtaskAccordionTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "600",
    flex: 1,
  },
  subtaskHeaderInput: {
    flex: 1,
    minHeight: 36,
    paddingVertical: 7,
  },
  subtaskHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  subtaskHeaderIconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#15262D",
    borderWidth: 1,
    borderColor: "#24424E",
  },
  subtaskStatusBadge: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    overflow: "hidden",
  },
  subtaskStatusBadgeCompleted: {
    color: "#67F0B7",
    backgroundColor: "#1D3A32",
  },
  subtaskStatusBadgePending: {
    color: "#9ED9E8",
    backgroundColor: "#234652",
  },
  subtaskAccordionBody: {
    borderTopWidth: 1,
    borderTopColor: "#233A45",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  subtaskEditActionsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginBottom: 2,
  },
  subtaskCompleteToggleRow: {
    flexDirection: "row",
    gap: 8,
  },
  subtaskCompleteToggleButton: {
    minWidth: 64,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2A4652",
    backgroundColor: "#15262D",
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  subtaskCompleteToggleButtonActive: {
    borderColor: "#70E1FF",
    backgroundColor: "#1C3640",
  },
  subtaskCompleteToggleText: {
    color: "#9AB3BF",
    fontSize: 13,
    fontWeight: "600",
  },
  subtaskCompleteToggleTextActive: {
    color: "#E5F7FF",
  },
  subtaskStatusOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  subtaskStatusOptionButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2A4652",
    backgroundColor: "#15262D",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  subtaskStatusOptionButtonActive: {
    borderColor: "#70E1FF",
    backgroundColor: "#1C3640",
  },
  subtaskStatusOptionText: {
    color: "#9AB3BF",
    fontSize: 13,
    fontWeight: "600",
  },
  subtaskStatusOptionTextActive: {
    color: "#E5F7FF",
  },
});