import { colors } from "@shared/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  dateText: {
    fontSize: 12,
    color: "#8FA3AD",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: colors.text,
    maxWidth: 230,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#1B2A30",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2B3B43",
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#F4C552",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  statusPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#10222A",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#1D3A45",
    marginBottom: 14,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#4DE3B1",
    marginRight: 8,
  },
  statusText: {
    fontSize: 12,
    color: "#69E0FF",
    fontWeight: "600",
    letterSpacing: 0.6,
  },
  heroCard: {
    backgroundColor: "#0E1C22",
    borderRadius: 20,
    padding: 20,
    marginBottom: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#16303A",
  },
  heroGlow: {
    position: "absolute",
    right: -40,
    top: -60,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "#0B4D6D",
    opacity: 0.4,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 16,
  },
  heroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(12, 32, 40, 0.8)",
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 8,
    alignSelf: "flex-start",
  },
  heroMetaText: {
    color: "#B8D7E6",
    fontSize: 13,
    marginLeft: 8,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 12,
  },
  sectionAction: {
    fontSize: 14,
    fontWeight: "500",
    color: "#54D2FF",
  },
  upNextRow: {
    paddingBottom: 10,
    paddingRight: 10,
  },
  eventCard: {
    width: 220,
    backgroundColor: "#1A2429",
    borderRadius: 16,
    padding: 16,
    marginRight: 14,
    borderWidth: 1,
    borderColor: "#23343C",
  },
  eventLead: {
    fontSize: 11,
    fontWeight: "600",
    color: "#3FD3FF",
    marginBottom: 8,
    letterSpacing: 0.6,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 10,
  },
  eventMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  eventMetaText: {
    fontSize: 12,
    color: "#8DA7B5",
    marginLeft: 6,
  },
  eventDivider: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#394B53",
    marginHorizontal: 10,
  },
  eventActionButton: {
    backgroundColor: "#12313C",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#1E3E4A",
  },
  eventActionText: {
    fontSize: 12,
    color: "#70E1FF",
    fontWeight: "600",
    textAlign: "center",
  },
  actionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  actionCard: {
    width: "48%",
    backgroundColor: "#1B2429",
    borderRadius: 16,
    padding: 16,
    minHeight: 120,
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#22353E",
  },
  actionIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#21313A",
    alignItems: "center",
    justifyContent: "center",
  },
  actionLabel: {
    fontSize: 14,
    color: colors.text,
    fontWeight: "600",
    lineHeight: 20,
  },
  bottomNav: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#151F24",
    borderRadius: 18,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#22323A",
  },
  bottomItem: {
    alignItems: "center",
    gap: 4,
  },
  bottomItemActive: {
    alignItems: "center",
    gap: 4,
  },
  bottomLabel: {
    fontSize: 10,
    color: "#6E808A",
  },
  bottomLabelActive: {
    fontSize: 10,
    color: "#54D2FF",
    fontWeight: "600",
  },
  scrollIndicatorContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
    marginBottom: 16,
    gap: 8,
  },
  scrollDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#2A3B43",
  },
  scrollDotActive: {
    width: 20,
    backgroundColor: "#54D2FF",
  },
  logoutButton: {
    marginHorizontal: 20,
    marginBottom: 20,
    paddingVertical: 14,
    backgroundColor: colors.error,
    borderRadius: 8,
    alignItems: "center",
  },
  logoutText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
});
