import { colors } from "@shared/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    padding: 4,
  },
  title: {
    fontSize: 20,
    fontWeight: "600",
    color: colors.text,
  },
  doneButton: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  section: {
    marginBottom: 32,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.secondary,
    marginBottom: 12,
  },
  everyRow: {
    flexDirection: "row",
    gap: 12,
  },
  intervalInput: {
    width: 100,
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 18,
    color: colors.text,
    textAlign: "center",
    backgroundColor: "#1A2429",
  },
  frequencySelector: {
    flex: 1,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    backgroundColor: "#1A2429",
  },
  frequencyText: {
    fontSize: 18,
    color: colors.text,
  },
  frequencyPicker: {
    marginTop: 8,
    backgroundColor: "#1A2429",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  frequencyOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  frequencyOptionText: {
    fontSize: 16,
    color: colors.text,
  },
  frequencyOptionTextActive: {
    color: colors.primary,
    fontWeight: "600",
  },
  weekdayRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  weekdayButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "transparent",
  },
  weekdayButtonActive: {
    backgroundColor: "#FF9500",
    borderColor: "#FF9500",
  },
  weekdayText: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.text,
  },
  weekdayTextActive: {
    color: "#000000",
    fontWeight: "600",
  },
  setTimeButton: {
    height: 50,
    justifyContent: "center",
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    marginBottom: 32,
    backgroundColor: "#1A2429",
    flexDirection: "row",
    alignItems: "center",
  },
  setTimeText: {
    fontSize: 16,
    color: colors.text,
    flex: 1,
  },
  clearTimeButton: {
    padding: 4,
  },
  dateInput: {
    height: 50,
    justifyContent: "center",
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "#1A2429",
  },
  dateText: {
    fontSize: 16,
    color: colors.text,
  },
  endOption: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    minHeight: 50,
  },
  radio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  radioActive: {
    borderColor: "#FF9500",
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#FF9500",
  },
  endOptionText: {
    fontSize: 16,
    color: colors.text,
    marginRight: 12,
  },
  endDateInput: {
    flex: 1,
    height: 50,
    justifyContent: "center",
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "#1A2429",
  },
  endDateText: {
    fontSize: 16,
    color: colors.text,
  },
  endDateTextDisabled: {
    color: colors.secondary,
    opacity: 0.5,
  },
  countInput: {
    width: 80,
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    color: colors.text,
    textAlign: "center",
    backgroundColor: "#1A2429",
    marginRight: 12,
  },
  countInputDisabled: {
    opacity: 0.5,
  },
});
