import { colors } from "@shared/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  statusContainer: {
    alignItems: 'center',
    marginBottom: 40,
    padding: 16,
    backgroundColor: '#1A2429',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#23343C',
  },
  statusText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginTop: 8,
  },
  sessionCountText: {
    fontSize: 14,
    color: '#8FA3AD',
    marginTop: 4,
  },
  focusStateContainer: {
    alignItems: 'center',
    padding: 32,
    borderRadius: 20,
    borderWidth: 2,
    marginBottom: 32,
  },
  focusStateText: {
    fontSize: 24,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 12,
  },
  focusScoreText: {
    fontSize: 32,
    fontWeight: '700',
    marginTop: 8,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#1A2429',
    borderRadius: 16,
    padding: 24,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: '#23343C',
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#8FA3AD',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sessionInfo: {
    backgroundColor: '#1A2429',
    borderRadius: 12,
    padding: 16,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: '#23343C',
  },
  sessionIdText: {
    fontSize: 14,
    color: '#8FA3AD',
    marginBottom: 4,
  },
  userIdText: {
    fontSize: 14,
    color: '#8FA3AD',
  },
  controlsContainer: {
    marginTop: 'auto',
  },
  startButton: {
    backgroundColor: '#4DE3B1',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  startButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
  },
  endButton: {
    backgroundColor: '#FF6B6B',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  endButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  disabledButton: {
    backgroundColor: '#2A3B43',
    elevation: 0,
    shadowOpacity: 0,
  },
});
