import { colors } from "@shared/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F1A1F",
    paddingHorizontal: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    color: colors.text,
    fontSize: 22,
    fontWeight: "700",
    marginRight: 44,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#1E3640",
    marginTop: 10,
  },
  content: {
    flex: 1,
    marginTop: 16,
  },
  contentContainer: {
    paddingBottom: 24,
  },
  formGroup: {
    marginBottom: 18,
    gap: 8,
  },
  label: {
    color: "#8AE8FF",
    fontSize: 16,
    marginBottom: 0,
    fontWeight: "700",
  },
  input: {
    backgroundColor: "#0F1A1F",
    borderWidth: 1,
    borderColor: "#223D47",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 16,
  },
  pickerInput: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pickerInputText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "500",
  },
  textArea: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  timeInput: {
    flex: 1,
  },
  subtaskCard: {
    backgroundColor: "#16242B",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#223D47",
    marginBottom: 10,
    overflow: "hidden",
    padding: 12,
  },
  subtaskContent: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  subtaskHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  subtaskTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    paddingRight: 8,
  },
  subtaskOrderBadge: {
    minWidth: 34,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: "#1D3B47",
    color: "#78E5FF",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  subtaskTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "600",
    flex: 1,
  },
  subtaskDescriptionInput: {
    minHeight: 74,
  },
  removeSubtaskButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#223D47",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F1A1F",
  },
  removeSubtaskText: {
    color: "#FF6B6B",
    fontSize: 16,
    fontWeight: "700",
  },
  addSubtaskButton: {
    marginTop: 8,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#223D47",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#16242B",
  },
  addSubtaskText: {
    color: "#78E5FF",
    fontSize: 13,
    fontWeight: "600",
  },
  helperText: {
    color: "#80A1AF",
    fontSize: 12,
    marginTop: 0,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: "#1E3640",
    paddingVertical: 12,
    marginTop: 8,
  },
  saveButton: {
    backgroundColor: "#78E5FF",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: "#0F1A1F",
    fontSize: 16,
    fontWeight: "700",
  },
  dateTimePickerColumn: {
    flex: 1,
    marginRight: 12,
  },
  dateTimePickerButton: {
    justifyContent: "center",
  },
  durationContainer: {
    backgroundColor: "#16242B",
    padding: 16,
    borderRadius: 8,
  },
  durationText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#78E5FF",
    marginTop: 8,
  },
  durationSubtaskLabel: {
    fontSize: 12,
    color: "#8AE8FF",
    marginTop: 4,
    fontStyle: "italic",
  },
});
